<a href="https://colab.research.google.com/github/Sottim/AIDA-Spring2023/blob/main/Week12_CreditRiskMode%3B_Rev_LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
dataset = pd.read_csv("Churn_Modelling.csv")
#Display the first five elements
dataset.head() 

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
X = dataset.iloc[:, 3:13].values
X
y = dataset.iloc[:,13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:,2] = labelencoder.fit_transform(X[:, 2])
X[:, 1] = labelencoder.fit_transform(X[:,1])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer 
#OneHOt Encoder has been applied to column 1
# I have given the ColumnTransformer function a name of my choice which is country
# The functionality has been passed onto the variable ct but still not applied to the data
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
# We shall now apply it on the data
X = ct.fit_transform(X)
X


array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
#

X = pd.DataFrame(X, columns = ["X1", "X2", "X3", "Credit Score", "Gender", "Age","Tenure", "Balance", "NumofProducts", "HasCrCard", "IsActive Member", "Estimated Salary"])
X

X1   X2   X3 Credit Score Gender Age Tenure    Balance NumofProducts  \
0     1.0  0.0  0.0          619      0  42      2        0.0             1   
1     0.0  0.0  1.0          608      0  41      1   83807.86             1   
2     1.0  0.0  0.0          502      0  42      8   159660.8             3   
3     1.0  0.0  0.0          699      0  39      1        0.0             2   
4     0.0  0.0  1.0          850      0  43      2  125510.82             1   
...   ...  ...  ...          ...    ...  ..    ...        ...           ...   
9995  1.0  0.0  0.0          771      1  39      5        0.0             2   
9996  1.0  0.0  0.0          516      1  35     10   57369.61             1   
9997  1.0  0.0  0.0          709      0  36      7        0.0             1   
9998  0.0  1.0  0.0          772      1  42      3   75075.31             2   
9999  1.0  0.0  0.0          792      0  28      4  130142.79             1   

     HasCrCard IsActive Member Estimated Salary  
0            1               1        101348.88  
1            0               1        112542.58  
2            1               0        113931.57  
3            0               0         93826.63  
4            1               1          79084.1  
...        ...             ...              ...  
9995         1               0         96270.64  
9996         1               1        101699.77  
9997         0               1         42085.58  
9998         1               0         92888.52  
9999         1               0         38190.78  

[10000 rows x 12 columns]

In [ ]:
# Fro the dataframe drop X1
# axis = 1 indicates where should Pthon look for the variable X1
#The answer is that it should look for X1 along the X-axis and hence axis is set to 1
# If looking along the Y-axis the axis shou;d be set to 0
#
 X = X.drop(["X1"], axis = 1)
 X
 #Apple = 1 - Bananas - Mangoes

IndentationError: ignored

In [ ]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y test_size = 0,2, random_state =0)

In [ ]:
from sklearn.preprocessiong import StandardScaler
sc = StandardScaler()
# Pass on the functionality to a new variabvle called sc
X_train = sc.fit_transform(X_train)
# The model is trained to recognise the mean and standard deviation of train data
# If it is working properly the test data using the mean and standard deviation of train data
X_test = sc.transform(X_test)
X_train

In [ ]:
import statsmodels.api as statsmodels
# Fitting Logistic Regression to the Training set 
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)
classifier = sm.Logit(y_train, X_train)
model = classifier.fit()
model.summery()


In [ ]:
import seaborn as sns
from sklearn import metrices

y_pred = model.predict(X_test)
y_pred = (y_pred > 0.45)
print("Accuracy: ", metrics.accuracy_socre(y_test, y_pred))
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot = True, fmt='');
